BASE_URL = "https://boombvaping.com/api/v2"
API_KEY ="75T3GOIJ5EBNL3TLC7MFRGS2UV1PKYK9WXL4LSRPTYWX3QJMPKNUQ8SOJMOCUURY"

TIMEOUT = 30
SYNC_PAGE_SIZE = 10
SYNC_PAGE_DELAY_SECONDS = 2.5
REQUEST_TIMEOUT = 60
AUTO_SYNC_MINUTES = 60
SUPABASE_URL = "https://myvizknnotmredrotljj.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "shereR"
SUPABASE_PUBLISHABLE_KEY = "shere"

CLOUD_BACKEND_HOST = "0.0.0.0"
CLOUD_BACKEND_PORT = 8788
CLOUD_BACKEND_WEBHOOK_TOKEN = "boomB-secret-token"